# Generated by Django 3.2 on 2021-07-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0002_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('usertype', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'login1',
                'managed': False,
            },
        ),
    ]
