# Generated by Django 3.2 on 2021-05-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyDetails',
            fields=[
                ('fid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('deptname', models.CharField(max_length=100)),
                ('phoneno', models.TextField()),
                ('email', models.TextField()),
                ('photo', models.TextField()),
            ],
        ),
    ]
