# Generated by Django 3.2 on 2021-05-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultydetails',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
