# Generated by Django 3.2 on 2021-05-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hod', '0002_alter_facultydetails_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('deptname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('hod', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
