# Generated by Django 3.2 on 2021-05-19 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hod', '0005_alter_facultydetails_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='facultydetails',
            table='faculty_details',
        ),
    ]
