# Generated by Django 3.2 on 2021-06-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hod', '0009_staffadvisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectClass',
            fields=[
                ('subjectid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('subject_title', models.TextField()),
                ('classid', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=30)),
                ('internal_passmark', models.IntegerField()),
                ('internal_mark', models.IntegerField()),
                ('external_pass_mark', models.IntegerField()),
                ('external_mark', models.IntegerField()),
            ],
            options={
                'db_table': 'subject_class',
                'managed': False,
            },
        ),
    ]
