# Generated by Django 3.2 on 2021-06-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hod', '0011_subjectallocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudDetails',
            fields=[
                ('admissionno', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('dob', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('religion', models.TextField(blank=True, null=True)),
                ('caste', models.TextField(blank=True, null=True)),
                ('year_of_admission', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('mobile_phno', models.TextField(blank=True, null=True)),
                ('land_phno', models.TextField()),
                ('address', models.TextField(blank=True, null=True)),
                ('rollno', models.TextField(blank=True, null=True)),
                ('rank', models.TextField(blank=True, null=True)),
                ('quota', models.TextField(blank=True, null=True)),
                ('school_1', models.TextField(blank=True, null=True)),
                ('regno_1', models.TextField(blank=True, null=True)),
                ('board_1', models.TextField(blank=True, null=True)),
                ('percentage_1', models.TextField()),
                ('school_2', models.TextField(blank=True, null=True)),
                ('regno_2', models.TextField(blank=True, null=True)),
                ('board_2', models.TextField(blank=True, null=True)),
                ('percentage_2', models.TextField()),
                ('no_chance1', models.TextField(blank=True, null=True)),
                ('name_last_studied', models.TextField()),
                ('courseid', models.TextField(blank=True, null=True)),
                ('branch_or_specialisation', models.TextField(blank=True, null=True)),
                ('branch_code', models.CharField(max_length=20)),
                ('image', models.TextField()),
                ('gate_score', models.IntegerField()),
                ('admission_type', models.CharField(max_length=30)),
                ('entry_sem', models.IntegerField()),
                ('exit_sem', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('blood', models.CharField(max_length=5)),
                ('image_status', models.CharField(blank=True, max_length=50, null=True)),
                ('tc_no_adm', models.CharField(blank=True, max_length=100, null=True)),
                ('tc_date_adm', models.DateField(blank=True, null=True)),
                ('date_of_admission', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stud_details',
                'managed': False,
            },
        ),
    ]
