# Generated by Django 3.2 on 2021-06-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hod', '0012_studdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.TextField()),
            ],
            options={
                'db_table': 'faculty_designation',
                'managed': False,
            },
        ),
    ]
