# Generated by Django 3.2 on 2021-05-19 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hod', '0004_alter_facultydetails_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facultydetails',
            options={'managed': False},
        ),
    ]
