# Generated by Django 3.2 on 2021-06-06 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hod', '0010_subjectclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectAllocation',
            fields=[
                ('classid', models.OneToOneField(db_column='classid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Hod.subjectclass')),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'subject_allocation',
                'managed': False,
            },
        ),
    ]
