# Generated by Django 3.2 on 2021-05-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hod', '0003_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultydetails',
            name='photo',
            field=models.TextField(),
        ),
    ]
