# Generated by Django 3.2 on 2021-05-20 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hod', '0006_auto_20210519_1225'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
    ]
